# -*- coding: utf-8 -*-
"""exnp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12VRJM_VbrUc941yvLdyIFte_KqmcaQzD
"""

# 평균, 분산, 표준편차
grades = [1, -2, 3, 4] # 변량
print(grades)
a = 10
print(a)

def show_grades(grades):
  for g in grades:
    print(g, end = ' ')
show_grades(grades)

def grades_sum(grades):
  tot = 0
  for g in grades:
    tot += g
  return tot
  
grades_sum(grades)

def grades_ave(grades):
  tot = grades_sum(grades)
  ave = tot / len(grades)
  return ave

grades_ave(grades)

# 편차 : 실제값과 평균값의 차이, 변량에서 평균을 뺀값
# 분산 : 편차를 제곱해서 평균을 구함
def grades_variance(grades):
    ave = grades_ave(grades)
    vari = 0
    for su in grades:
      vari += (su - ave) ** 2
    return vari / len(grades) # 모집단으로 계산
    return vari / (len(grades) - 1) # 표본집단으로 계산
grades_variance(grades)

import math
def grades_std(grades): # 표준편차 : 분산에 루트를 씌움
    return grades_variance(grades) ** 0.5
    # return math.sqrt(grades_variance(grades))
grades_std(grades)

# numpy 제공 함수
import numpy as np
print('합은 ', np.sum(grades))
print('평균은 ', np.mean(grades))
print('분산은 ', np.var(grades))
print('표준편차는 ', np.std(grades))

print('평균은 ', np.average(grades))
print('평균은(nan무시) ', np.nanmean(grades))